image: jangrewe/gitlab-ci-android

stages:
  - test
  - build

# debug state
test:
  stage: test
  script:
    - ./gradlew --stacktrace clean assembleDebug
  artifacts:
    paths:
      - mainapp/build/outputs/

# release state
#build:
#  stage: build
#  script:
#    - ./gradlew --stacktrace clean assembleRelease
#  artifacts:
#    paths:
#      - app/build/outputs/